name: 'Golang PR Coverage'
description: 'Check your Pull Request testing coverage'

inputs:
  working-directory:
    description: 'Directory in which to run tests'
    default: '.'

outputs:
  cov-diff:
    description: "Coverage results diff"
    value: ${{ steps.cov-diff.outputs.cov-diff }}

runs:
  using: "composite"
  steps:
    - name: Calculate base coverage
      shell: bash
      run: |
        git checkout ${{ github.base_ref }}
        cd ${{ inputs.working-directory }}
        make test > /dev/null/
        go tool cover -func=c.out | tee /tmp/cov_base | tail -n1 | sed 's/%//g' | awk '{printf "cov_base=%s", $3}' >> $GITHUB_ENV

    - name: Calculate HEAD coverage
      shell: bash
      run: |
        git checkout ${{ github.head_ref }}
        cd ${{ inputs.working-directory }}
        make test > /dev/null/
        go tool cover -func=c.out | tee /tmp/cov_head | tail -n1 | sed 's/%//g' | awk '{printf "cov_head=%s", $3}' >> $GITHUB_ENV

    - name: Display coverage diff
      id: cov-diff
      shell: bash
      run: |
        diff /tmp/cov_base /tmp/cov_head | tee /tmp/diff
        content=$(cat /tmp/diff)
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=cov-diff::$content"

    - name: Check if coverage has decreased
      shell: bash
      run: awk 'BEGIN{ if (${{ env.cov_base }} > ${{ env.cov_head }}) {print "::error::Coverage has decreased from ${{ env.cov_base }}% to ${{ env.cov_head }}%"; exit 1;} else {print "OK! Total coverage is ${{ env.cov_head }}%"}}'
